name: OnlyOffice Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build inside Docker
        run: |
          docker run --rm -v $(pwd):/root ubuntu:22.04 bash /root/builder_entrypoint.sh
